### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Celestialchips** [hsdn/tera-guide-core#1]
[06:48:32.435] [tera-guide] ERROR: Warning!
Depended module "tera-guide-core" needed for TERA-Guide is not installed!
Please download and install: https://github.com/hsdn/tera-guide-core

[06:48:32.436] [mods] ERROR: Module "Guide" (tera-guide) could not be applied to server connection!
[06:48:32.436] [mods] ERROR: Please contact the module's author: https://github.com/hsdn/tera-guide/issues
[06:48:32.437] TypeError: mod.require.tera-guide-core.load is not a function
    at new exports.NetworkMod (C:\...\...\AppData\Local\Programs\TeraToolbox\mods\tera-guide-master\index.js:5:34)
    at Mod.loadNetworkInstance (C:\...\...\AppData\Local\Programs\TeraToolbox\bin\mod.js:595:31)
    at ModManager.loadNetwork (C:\...\...\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:252:20)
    at C:\...\...\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:233:22
    at Map.forEach (<anonymous>)
    at ModManager.loadAllNetwork (C:\...\...\AppData\Local\Programs\TeraToolbox\bin\mod-manager.js:231:25)
    at Socket.<anonymous> (C:\...\...\AppData\Local\Programs\TeraToolbox\bin\connection-manager.js:59:33)
    at Socket.emit (events.js:228:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1120:10)

**Comment by justkeepquiet** [comment]
Please check https://github.com/hsdn/tera-guide/issues/43
